# Generated by Django 5.2.12 on 2026-07-22 08:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_rename_book_id_book_id'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrowed_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BORROWED', 'Borrowed'), ('RETURNED', 'Returned')], default='BORROWED', max_length=10)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fine_paid', models.BooleanField(default=False)),
                ('fine_paid_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_books', to='books.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_books', to='members.member')),
            ],
            options={
                'db_table': 'borrowings',
                'ordering': ['-borrowed_date'],
            },
        ),
    ]
