[pytest]
DJANGO_SETTINGS_MODULE=config.settings
python_files=test_*.py *_tests.py # Find files starting with "test_" OR ending with "_tests.py"

#however this is not needed because pytest has default with below code.Only needed when you want to change the default naming convention.
python_classes = Test*          # Test classes start with "Test"
python_functions = test_*       # Test functions start with "test_"