# Generated by Django 5.2.12 on 2026-07-18 13:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('total_copies', models.PositiveIntegerField()),
                ('available_copies', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='books', to='authors.author')),
            ],
            options={
                'db_table': 'books',
                'ordering': ['title'],
                'constraints': [models.CheckConstraint(condition=models.Q(('available_copies__lte', models.F('total_copies'))), name='available_copies_lte_total_copies')],
            },
        ),
    ]
